version: '2'
services:
 node1:
  image: akka-artery-example:1.0.3
  container_name: node1
  hostname: node1
  volumes:
   - ./docker/node1/:/opt/docker/conf/
   - ./docker/jolokia/:/opt/jolokia/
  ports:
    - 7071:7070
    - 8558:8558
 node2:
  image: akka-artery-example:1.0.3
  container_name: node2
  hostname: node2
  depends_on:
    - node1
  volumes:
   - ./docker/node2/:/opt/docker/conf/
   - ./docker/jolokia/:/opt/jolokia/
  ports:
    - 7072:7070
    - 8559:8558
 node3:
  image: akka-artery-example:1.0.3
  container_name: node3
  hostname: node3
  depends_on:
    - node1
    - node2
  volumes:
   - ./docker/node3/:/opt/docker/conf/
   - ./docker/jolokia/:/opt/jolokia/
  ports:
    - 7073:7070
    - 8560:8558
